### ISSUE TITLE
Some error during deploying the project on single 3090

### ISSUE THREAD

**Issue by Biglemon-Ning** [SAI990323/TALLRec#21]
Hello~, I encountered an error when reproducing TALLRec on single 3090. The details are shown as follows:
![image](https://github.com/SAI990323/TALLRec/assets/77471999/16c2e31a-ab27-4cd9-aaf7-58530bb7f802)
Can you give me some advice about how to solve this error if you have encountered it before?

**Comment by zyujing** [comment]
how did you fix this problem？ i met it too
