### ISSUE TITLE
Alpaca-LoRA weight

### ISSUE THREAD

**Issue by mayhugotong** [SAI990323/TALLRec#22]
May I ask which Alpaca-LoRA weight you are using for your RT phase?
Is it the Tleon one?
There's model size mismatching error.

**Comment by SAI990323** [comment]
We did not use the publicly available Alpaca-LoRA model. If you are using it, please align the parameters related to LoRA in your script with the model you are using.

**Comment by Biglemon-Ning** [comment]
How to align the parameters?

**Comment by Biglemon-Ning** [comment]
How to align the parameters? If possible, can you provide the LoRA model or the link to the used LoRA model?

**Comment by Biglemon-Ning** [comment]
Can you publish the used LoRA weights? Thanks!

**Comment by SAI990323** [comment]
If you download the model from the huggingface,  you could click the "Files and Versions" and choose the adapter_config.json, you will see the hyper-parameters for LoRA.
![image](https://github.com/SAI990323/TALLRec/assets/40531945/12d3cff2-ce3e-43ee-a19e-8c2e9359dd77)
