### ISSUE TITLE
> The following is an interception of some intermediate results, and the probability of predicting yes is also very close：

### ISSUE THREAD

**Issue by liujianwei2023** [SAI990323/TALLRec#23]
> The following is an interception of some intermediate results, and the probability of predicting yes is also very close：
> 
> ['Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. # noqa: E501\n\n### Instruction:\nGiven the user's preference and unpreference, identify whether the user will like the target movie by answering "Yes." or "No.".\n\n### Input:\nUser Preference: "Paris, Texas (1984)", "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)"\nUser Unpreference: "Kalifornia (1993)"\nWhether the user will like the target movie "Perez Family, The (1995)"?\n\n### Response:\nYes.\n\n### Explanation:\nThe user prefers "Paris, Texas (1984)", "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (199', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. # noqa: E501\n\n### Instruction:\nGiven the user's preference and unpreference, identify whether the user will like the target movie by answering "Yes." or "No.".\n\n### Input:\nUser Preference: "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)"\nUser Unpreference: "Kalifornia (1993)", "Perez Family, The (1995)"\nWhether the user will like the target movie "Jurassic Park (1993)"?\n\n### Response:\nYes.\n\n### Explanation:\nThe user prefers "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)" and unpreferences "Kalifornia'] ['Yes.\n\n### Explanation:\nThe user prefers "Paris, Texas (1984)", "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (199', 'Yes.\n\n### Explanation:\nThe user prefers "Rebel Without a Cause (1955)", "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)" and unpreferences "Kalifornia'] [[0.5731707811355591, 0.4268292486667633], [0.5828027129173279, 0.4171972870826721]] 1it [00:06, 6.24s/it]['Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. # noqa: E501\n\n### Instruction:\nGiven the user's preference and unpreference, identify whether the user will like the target movie by answering "Yes." or "No.".\n\n### Input:\nUser Preference: "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)"\nUser Unpreference: "Kalifornia (1993)", "Perez Family, The (1995)"\nWhether the user will like the target movie "Manhattan Murder Mystery (1993)"?\n\n### Response:\nYes.\n\n### Explanation:\nThe user prefers "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)" and unpreferences "Kalifornia (1', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. # noqa: E501\n\n### Instruction:\nGiven the user's preference and unpreference, identify whether the user will like the target movie by answering "Yes." or "No.".\n\n### Input:\nUser Preference: "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)", "Manhattan Murder Mystery (1993)"\nUser Unpreference: "Kalifornia (1993)", "Perez Family, The (1995)"\nWhether the user will like the target movie "Sleeper (1973)"?\n\n### Response:\nYes.\n\n### Explanation:\nThe user prefers "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)", "Manhattan Murder Mystery (1993)" and unpreferences "Kalifornia (199'] ['Yes.\n\n### Explanation:\nThe user prefers "Return of the Pink Panther, The (1974)", "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)" and unpreferences "Kalifornia (1', 'Yes.\n\n### Explanation:\nThe user prefers "Ace Ventura: Pet Detective (1994)", "Magnificent Seven, The (1954)", "Star Trek: The Wrath of Khan (1982)", "Cat People (1982)", "Orlando (1993)", "Dave (1993)", "Jurassic Park (1993)", "Manhattan Murder Mystery (1993)" and unpreferences "Kalifornia (199'] [[0.5806307196617126, 0.41936925053596497], [0.5781132578849792, 0.42188674211502075]]

Have you verified your stored LoRA model? Is the size of the model appropriate?

_Originally posted by @SAI990323 in https://github.com/SAI990323/TALLRec/issues/20#issuecomment-1704585600_

**Comment by liujianwei2023** [comment]
![image](https://github.com/SAI990323/TALLRec/assets/134259354/bc95cd55-281e-4301-98cc-dd872168512f)

**Comment by SAI990323** [comment]
> ![image](https://user-images.githubusercontent.com/134259354/265319688-bc95cd55-281e-4301-98cc-dd872168512f.png)

As you can see, your adapter_model.bin is only 4.0K. The probable cause for this issue might be related to the version of the "peft" package. You may need to modify the code accordingly based on the version you are utilizing, or alternatively, revert to a previous version.

**Comment by liujianwei2023** [comment]
![](https://user-images.githubusercontent.com/134259354/265319688-bc95cd55-281e-4301-98cc-dd872168512f.png)

**Comment by liujianwei2023** [comment]
Thanks for your patience, I'll try again

**Comment by liujianwei2023** [comment]
I tried the peft version you provided and trained for 10 epochs. The bin file is still about 4k. Isn’t the model the optimizer.pt file?
![image](https://github.com/SAI990323/TALLRec/assets/134259354/8a85138e-ac32-4d33-a93b-e0c9f817b2ef)
![image](https://github.com/SAI990323/TALLRec/assets/134259354/b82ff1e2-d82d-4dfa-8428-901c926409cb)
![image](https://github.com/SAI990323/TALLRec/assets/134259354/1ae5abd9-5750-40c8-b654-2ce8a3f32d0a)

**Comment by liujianwei2023** [comment]
Thanks, problem solved.
I have a new question, what is the meaning of 8241 and 3782 in the code?
labels_index = torch.argwhere(torch.bitwise_or(labels == 8241, labels == 3782))

**Comment by SAI990323** [comment]
> Thanks, problem solved. I have a new question, what is the meaning of 8241 and 3782 in the code? labels_index = torch.argwhere(torch.bitwise_or(labels == 8241, labels == 3782))

Here we have taken a shortcut, in reality, it corresponds to the token ID of "Yes" and "No".

**Comment by liujianwei2023** [comment]
Thanks, I would like to further ask how to locate the index of a specific token id (yes/no), and then does this index must be in the response?

**Comment by liujianwei2023** [comment]
![image](https://github.com/SAI990323/TALLRec/assets/134259354/e627a33e-cadb-419f-aafc-8f2d5ffb0b2b)
![image](https://github.com/SAI990323/TALLRec/assets/134259354/fac7f262-c0e8-457c-a05e-6408207f6223)

**Comment by SAI990323** [comment]
There is a lot of "Yes", "No" in LlaMA Tokenizer, you should  check the token ID of your input & output

**Comment by liujianwei2023** [comment]
thanks

**Comment by codediyi** [comment]
> Thanks for your patience, I'll try again



> > ![image](https://user-images.githubusercontent.com/134259354/265319688-bc95cd55-281e-4301-98cc-dd872168512f.png)
> 
> As you can see, your adapter_model.bin is only 4.0K. The probable cause for this issue might be related to the version of the "peft" package. You may need to modify the code accordingly based on the version you are utilizing, or alternatively, revert to a previous version.

**Comment by codediyi** [comment]
> > ![image](https://user-images.githubusercontent.com/134259354/265319688-bc95cd55-281e-4301-98cc-dd872168512f.png)
> 
> As you can see, your adapter_model.bin is only 4.0K. The probable cause for this issue might be related to the version of the "peft" package. You may need to modify the code accordingly based on the version you are utilizing, or alternatively, revert to a previous version.

How do I go about fixing this, I save these files as only 4k as well?

**Comment by SAI990323** [comment]
> > > ![image](https://user-images.githubusercontent.com/134259354/265319688-bc95cd55-281e-4301-98cc-dd872168512f.png)
> > 
> > 
> > As you can see, your adapter_model.bin is only 4.0K. The probable cause for this issue might be related to the version of the "peft" package. You may need to modify the code accordingly based on the version you are utilizing, or alternatively, revert to a previous version.
> 
> How do I go about fixing this, I save these files as only 4k as well?

make sure your bitsandbytes == 0.3.0 or you need to fix the code
