### ISSUE TITLE
Weights for instruction tuning model

### ISSUE THREAD

**Issue by saksham20aggarwal** [SAI990323/TALLRec#24]
Hi! It seems you have retrained the instruction tuning model with [alpaca-lora](https://github.com/tloen/alpaca-lora) repo with some changes in hyperparameters and not used the official weghts provided by them. Can you please share the retrained weights for instruction tuning and also recommendation tuning (final weights) if possible? 
(I have a V100 GPU which does not support training with FP16 which is making it a bit difficult for me to train.)

**Comment by SAI990323** [comment]
Actually, we use their recommended parameters, the model is now [uploading](https://github.com/SAI990323/TALLRec/tree/5899e3037e9d7cf58176dc165701ce70a0664ab5/alpaca-lora-7B).
