### ISSUE TITLE
The installed version of bitsandbytes was compiled without GPU support. 

### ISSUE THREAD

**Issue by LanPangxiang** [SAI990323/TALLRec#27]
UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

How to solve this problem and change the LD_LIBRARY_PATH?

**Comment by SAI990323** [comment]
I am sotry about that i never seen this problem, maybe you need to leave an issue on the bitsandbytes
