### ISSUE TITLE
Question About the Ablation Study

### ISSUE THREAD

**Issue by xiaxin1998** [SAI990323/TALLRec#28]
Dear Author,

Your paper is very great. After reading your experiments, I have a question.
In ablation study, you design 'IT' and 'IT+RT' versions to do comparison. 
From that figure, we can see that when the number of samples is zero, IT has different performance with 'IT+RT'.
I don't understand why. In my eyes, the number of samples refer to the number of samples in the recommendation tuning stage.
You firstly do instruction tuning using Alpaca and then do recommendation tuning in Book or Movie. When the number of samples is 0, IT is same with IT+RT.

Thanks! Looking forward to your reply.

**Comment by SAI990323** [comment]
Actually, the point you see is when the number of samples is 1. We do not include the point where the number of samples is 0 in the figure. We Apologize for any confusion caused.
