### ISSUE TITLE
The meaning of documents provided in drive.google

### ISSUE THREAD

**Issue by zhuanask** [SAI990323/TALLRec#38]
What are the model parameters provided in drive.google? 
What I understand is that alpaca-lora-7B/adapter_model.bin is the parameter fine-tuned after the first stage instruction tuning, and alpaca-lora-7B/checkpot-800(600/1000) are the parameters after the second stage recommendation tuning, is that right?

**Comment by kkkMeng** [comment]
尊敬的作者您好，请问这个意思是说second finetune stage最终的lora weight没有在google drive里面吗？

**Comment by kkkMeng** [comment]
尊敬的作者您好，请问如果想用您训练好的结果直接在evaluate上面做，base_model 和 output_dir 里应该放哪个文件呢？
