### ISSUE TITLE
Code for reproducing the AUC results for baseline (GRU,etc)

### ISSUE THREAD

**Issue by elloza** [SAI990323/TALLRec#42]
Congratulations for the great work and for sharing it!

I was wondering if the code to reproduce the baselines results in both datasets is available (maybe I have overlooked it).

If not, could you share it?

Thanks a lot.

**Comment by SAI990323** [comment]
Our code is based on this [repo](https://github.com/YangZhengyi98/DROS), For more details, you can send me this [email](baokq@mail.ustc.edu.cn), because I don’t often check the email address bound to GitHub. I’m very sorry about that.
