### ISSUE TITLE
How to use TALLRec ,尊敬的作者您好，诚恳请教您如何去使用您的TALLRec框架

### ISSUE THREAD

**Issue by Excy-an** [SAI990323/TALLRec#43]
目前以及根据您的ReadMe文件中的Training阶段介绍，初步训练了一下，目前再第二阶段evaluate.py步骤出现了一些问题，因为再ReadME文件中可能介绍有限，麻烦问题下这篇工作具体的复现流程是怎么样的呀？如何去使用TALLRec框架去执行推荐任务呀，非常感谢！！！！

**Comment by SAI990323** [comment]
您好，请问具体的问题是什么呢？
