### ISSUE TITLE
Experiments Details

### ISSUE THREAD

**Issue by remember00000** [SAI990323/TALLRec#45]
请问实验机器，epoch数，每个epoch运行时间， 总时间等实现细节是怎么样的呢？

**Comment by SAI990323** [comment]
对于这个实验，我们尝试过在单张3090或者单张A40上运行代码，epoch数设置的比较大，但是设置了ealrystop=5（如果连续5个epoch 验证集loss不下降停止训练），每个epoch运行时间与样本数绑定，总的运行时间大约是3～4h会收敛，更多的参数细节请参照bash脚本，谢谢
