### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by NicholasEinstein** [SAI990323/TALLRec#50]
作者你好，我在运行你的代码时候出现了
![QMROEQY(ZHVZ~VU6_Q{(2SV](https://github.com/SAI990323/TALLRec/assets/72395638/b116bf6a-8155-435f-97ae-edf66ca3f080)

这个情况，请问是什么原因呢

**Comment by Albertchamberlain** [comment]
same problem

**Comment by Albertchamberlain** [comment]
Can you help me to solve this problem?

**Comment by NicholasEinstein** [comment]
> Can you help me to solve this problem?

adapter_model.bin this file . you need install Git LFS .

**Comment by lw-xundong** [comment]
> > Can you help me to solve this problem?
> 
> adapter_model.bin this file . you need install Git LFS .

hi i install the GIT LFS,but i meet the same question.

"#  git lfs install
Updated Git hooks.
Git LFS initialized.
"

then also meet:
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by xurong-liang** [comment]
I got the same problem after `git lfs` installation and initialization. Do you guys find the solution?

**Comment by Lw1244204021** [comment]
I find a solution in https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key

you can try :
Remove the cloned project
Install [git lfs](https://git-lfs.github.com/): sudo apt-get install git-lfs
Set up git lfs for your user account: git lfs install
Clone the project again.

**Comment by lw-xundong** [comment]
> I got the same problem after `git lfs` installation and initialization. Do you guys find the solution?

I find a solution in https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key

you can try :
Remove the cloned project
Install [git lfs](https://git-lfs.github.com/): sudo apt-get install git-lfs
Set up git lfs for your user account: git lfs install
Clone the project again.

**Comment by xurong-liang** [comment]
Thanks for replying. I tried the solution you mentioned but the problem doesn't go away. I ended up modifying the model saving and loading methods and training a Llama-2-7b model from scratch myself.
