### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by NicholasEinstein** [SAI990323/TALLRec#51]
作者你好，我运行你的evaluate，使用的是你提供的book test的数据，我发现会出现显存爆掉的问题
![1709459902384](https://github.com/SAI990323/TALLRec/assets/72395638/68893f8d-3cd2-459e-8f45-bf6b046c5201)

当将batchsize调为1以后
![1709459937027](https://github.com/SAI990323/TALLRec/assets/72395638/4356a66d-04f3-4fd5-8a49-9109ca329c4e)

才能够正常运行，即使如此显存占用也很大，我的gpu是24gb的
![1709459985248](https://github.com/SAI990323/TALLRec/assets/72395638/5a56faa4-afc5-4863-b5ff-3e1e76ffef8c)

请问这是正常的吗

**Comment by SAI990323** [comment]
看起来是正常的, batchsize可以适当在加大一点，根据您的显存占用进行调整，如果我没记错的话24g的情况下batch可以开到4或8.
