### ISSUE TITLE
作者您好，我想请教您，您是在SASRec中是如何定义历史序列和目标标签的呢？

### ISSUE THREAD

**Issue by swordqiqi** [SAI990323/TALLRec#54]
看了您的部分回答，注意到在SASRec中您把目标标签设置为喜欢和不喜欢，但是在历史的交互信息中，似乎不包含关于喜欢与不喜欢的这种信息。请问您这是如何处理的呢？

**Comment by SAI990323** [comment]
We have reproduced the results and provided a download link at: https://rec.ustc.edu.cn/share/06dc8240-f8a6-11ee-9485-33ade2b15b8a. The password is: 235q. The specific method employed is the one mentioned in the paper “Unbiased Sequential Recommendation with Latent Confounders.” Should you have any questions, please feel free to contact us.

**Comment by swordqiqi** [comment]
谢谢您！！！请问您还保存有其他baseline的代码么，我在复现其他baseline时也遇到了相同的问题，比如GRU和Caser。谢谢！
