### ISSUE TITLE
bookcrossing数据集处理问题

### ISSUE THREAD

**Issue by ccTreasure** [SAI990323/TALLRec#57]
如题，在bx-book-ratings中，一共有1149780条用户评价，其中716109条即约62%的用户评分为0。根据我网上搜寻的结果，0是用户的默认评分，即未评分。我想知道，作者您是否对这部分数据进行了处理。

**Comment by SAI990323** [comment]
你好，这部分user我们是去掉了的，在文中我们有提及“The BookCrossing dataset has user ratings (1-10) and textual descriptions of books, such as the information of ‘Book-Author’ and ‘Book-Title’”
