### ISSUE TITLE
Evaluation efficiency

### ISSUE THREAD

**Issue by ysh-1998** [SAI990323/TALLRec#8]
I apologize for reaching out again. I have conducted an evaluation of the movie dataset and noticed that the process takes approximately two hours. I want to inquire if this duration is considered normal for this dataset.

Furthermore, during the testing process, it seems that the data is not being inputted in batches. I'm curious to understand the rationale behind this decision.

I appreciate your time and assistance.

**Comment by SAI990323** [comment]
We are sorry for not releasing the evaluation code with multi-batch, now the evaluate.py has been updated
