### ISSUE TITLE
is  "train_on_input" important

### ISSUE THREAD

**Issue by LifangD** [SAI990323/TALLRec#9]
since the movie's title is a little bit different from natural language, will the "train_on_important" be the crucial parameter?
And is there any ablation study result about it?

**Comment by LifangD** [comment]
since the movie's title is a little bit different from natural language,  will the "train_on_important" be the crucial parameter?
And is there any ablation study result about it?

**Comment by SAI990323** [comment]
We do not conduct such experiments, but I suppose you can of course set "train_on_input" as False and set the historical information in the "instructions".
